### ISSUE TITLE
ImportError: No module named models.complex

### ISSUE THREAD

**Issue by weibo053** [ChihebTrabelsi/deep_complex_networks#11]
When I run the example code, it gives me this error, please help. Thanks. 

deep_complex_networks$ train.py shallow_model --in-memory --model=shallow_convnet --local-data data/musicnet_11khz.npz
Using Theano backend.
Traceback (most recent call last):
  File "/home/bowei/miniconda2/bin/train.py", line 4, in <module>
    __import__('pkg_resources').run_script('DeepComplexNetworks==1', 'train.py')
  File "/home/bowei/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bowei/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "/home/bowei/miniconda2/lib/python2.7/site-packages/DeepComplexNetworks-1-py2.7.egg/EGG-INFO/scripts/train.py", line 16, in <module>
    
ImportError: No module named models.complex

**Comment by handale88** [comment]
I have also got the same error. If you find the solution, please let me know as well... :(

**Comment by OisinMoran** [comment]
So I had this same problem. What the file is trying to do is import a local package (one of the ones downloaded) but it doesn't know where to find it. In `Train.py` if you change this:
```python
import musicnet.models.complex
```
to this:
```python
import sys
# Change this to your own equivalent path
path = '/home/oisin/deep_complex_networks/musicnet' 
if path not in sys.path:
   sys.path.insert(0, path)

import musicnet.models.complex
```
it gets rid of _that_ error, but now I have a new (but similar) error:

```pytb
Using TensorFlow backend.
Traceback (most recent call last):
  File "scripts/train.py", line 21, in <module>
    import musicnet.models.complex
  File "/home/oisin/deep_complex_networks/musicnet/musicnet/models/complex/__init__.py", line 19, in <module>
    from complexnn import ComplexConv1D, ComplexBN, ComplexDense, GetReal
  File "/home/oisin/tensorflow/lib/python3.5/site-packages/DeepComplexNetworks-1-py3.5.egg/complexnn/__init__.py", line 8, in <module>
ImportError: No module named 'bn'
```

**Comment by OisinMoran** [comment]
@weibo053 and @handale88: Also make sure you are in the `deep_complex_networks-master/musicnet` directory and not just in `deep_complex_networks-master`. Have you both solved this issue yet?
