### ISSUE TITLE
Mímir IOError

### ISSUE THREAD

**Issue by OisinMoran** [ChihebTrabelsi/deep_complex_networks#20]
After running all the commands exactly as shown in the `README.md`, when executing the first line of step 2 in the MusicNet section, notably:

```bash
train.py shallow_model --in-memory --model=shallow_convnet --local-data data/musicnet_11khz.npz
```

I am getting this error:

```bash
Traceback (most recent call last):
  File "/home/oisin/DCN/bin/train.py", line 4, in <module>
    __import__('pkg_resources').run_script('DeepComplexNetworks==1', 'train.py')
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/DeepComplexNetworks-1-py2.7.egg/EGG-INFO/scripts/train.py", line 142, in <module>
    
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/DeepComplexNetworks-1-py2.7.egg/EGG-INFO/scripts/train.py", line 112, in main
    
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/mimir/logger.py", line 71, in Logger
    handlers.append(GzipJSONHandler(root))
  File "/home/oisin/DCN/local/lib/python2.7/site-packages/mimir/handlers.py", line 134, in __init__
    stream = gzlog.GZipLog(filename)
  File "gzlog/gzlog.pyx", line 89, in mimir.gzlog.GZipLog.__init__
  File "gzlog/gzlog.pyx", line 26, in mimir.gzlog.Gzlog.__cinit__
IOError
```

I am running this in a virtual environment with Python 2.7 and my `~/.keras/keras.json` looks like:
```json
{
    "backend": "theano",
    "epsilon": 1e-07,
    "floatx": "float32",
    "image_data_format": "channels_last"
}
```

Any help at all in trying to fix this would be greatly appreciated.

**Comment by OisinMoran** [comment]
This was solved by `sudo grep -rnw . -e 'serdyuk'` and changing the listed files to contain the correct file location.

**Comment by OisinMoran** [comment]
For anyone who gets the same error, I think this issue is solved by creating the directories:
`deep_complex_networks-master/musicnet/models/` 
&
`deep_complex_networks-master/musicnet/models/chkpts/`

Which can be done with the command:
```bash
mkdir -p models/chkpts
```
while in the `deep_complex_networks-master/musicnet` directory.

**Comment by StevenLOL** [comment]
Thanks
