### ISSUE TITLE
utilsextension DLL load failed

### ISSUE THREAD

**Issue by MICHAEL-ZF** [ChihebTrabelsi/deep_complex_networks#23]
have installed setup.py, but met with the problem
`Using Theano backend.
Traceback (most recent call last):
  File "scripts/run.py", line 237, in <module>
    main(sys.argv)
  File "scripts/run.py", line 235, in main
    return d.__subcmdfn__(d)
  File "scripts/run.py", line 193, in run
    import training;training.train(d)
  File "E:\Python_Project\Python2.7\ComplexNet\deep_complex_networks-master\scripts\training.py", line 28, in <module>
    from   kerosene.datasets                     import svhn2
  File "E:\Program\Anaconda2\envs\ComplexNet\lib\site-packages\kerosene\datasets\svhn2.py", line 2, in <module>
    import fuel.datasets
  File "E:\Program\Anaconda2\envs\ComplexNet\lib\site-packages\fuel\datasets\__init__.py", line 5, in <module>
    from fuel.datasets.hdf5 import H5PYDataset
  File "E:\Program\Anaconda2\envs\ComplexNet\lib\site-packages\fuel\datasets\hdf5.py", line 8, in <module>
    import tables
  File "E:\Program\Anaconda2\envs\ComplexNet\lib\site-packages\tables\__init__.py", line 90, in <module>
    from .utilsextension import (get_pytables_version, get_hdf5_version, blosc_compressor_list,blosc_compcode_to_compname_ as blosc_compcode_to_compname,blosc_get_complib_info_ as blosc_get_complib_info)
ImportError: DLL load failed`

tried installing with conda and pycharm.
I am working on windows10, should this be the problem?

**Comment by dmitriy-serdyuk** [comment]
Sorry, windows is not supported. See #22
